# Generated by Django 2.2 on 2020-08-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealStateArticles',
            fields=[
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RealStateNews',
            fields=[
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
        ),
    ]
