# Generated by Django 2.2 on 2020-08-10 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RealStateArticles',
            new_name='RealStateArticle',
        ),
    ]
